language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
install:
  - pip install six ordereddict
  - pip install pytest pytest-cov pytest-pep8
  - pip install coveralls
script:
  - py.test tests --pep8 -v --cov xmodels --cov-report term-missing
after_success:
  - coveralls
